### ISSUE TITLE
Building for Linux

### ISSUE THREAD

**Issue by Serasar** [FreaKzero/ssgl-doom-launcher#3]
Is it possible to build this on Linux? Also, which parts of mono it requires?

**Comment by FreaKzero** [comment]
Hi!
Its built in NWJS - so no Mono required at all. I have no Linux builds yet because of a few reasons.
1. Main Feature is Building Random Maps via Oblige direct in the Launcher - Since Oblige isnt available for Linux- and there are other Frontends/Launchers out there i wasnt expecting much Linux users when Oblige is for them not available.

2. I have no Linux machine right now - OR anyone who can test my builds. 
3. I have to refactor some things before it can run on Linux environments (i think)
4. It was/is planned to make Linux builds.

When you are interrested i can make you an actual testbuild - just say me what Arch you need (32 or 64)

**Comment by FreaKzero** [comment]
Did a grunt-builder for linux in the dev branch:
https://github.com/FreaKzero/ssgl-doom-launcher/tree/dev

Howto install all of that is described in the Readme, you will need NodeJS, Bower and Grunt for building. Rest is described in the Readme.

https://github.com/FreaKzero/ssgl-doom-launcher/commit/82f7dd6c3d950e06a248fc019318b1c89467b197

**Comment by FreaKzero** [comment]
Little update: 
Have to refactor some things to get this bugfree on Linux (It builds - and it runs - but Paths are fucked up obviously - have to research how to make paths crossplattform)

Will Integrate Chocolate Doom Support since its pretty popular on Linux Systems

**Comment by FreaKzero** [comment]
@Serasar 
News from the Front:
Neither zDoom nor gzDoom can run on an Virtualmachine - but Zandronum can:
![ssgltux](https://cloud.githubusercontent.com/assets/6339036/10425238/298f1d7e-70d6-11e5-8c9e-c5d8467eb4cc.gif)

So can you say me what Sourceports you are actually using ? zDoom or gzDoom would be nice so i can confirm this 2 are functioning too.

Just need to know what you need: 32bit or 64bit then ill build for you a Testversion.

**Comment by Serasar** [comment]
I currently use Zandronum, but I can test zDoom and gzDoom for you too. 64bot would be preferable

**Comment by FreaKzero** [comment]
Since i cant upload Files larger as 10MB here - heres a Google Drive link:
This is a "developer" version of the thing with the Toolbar - when something acts strange or wont function click on the "Hamburger" for logfiles (havent done proper logging yet)

https://drive.google.com/file/d/0B8iRufbwfROiUmhKQ2docWdTRUk/view?usp=sharing

**Comment by Serasar** [comment]
Works on zdoom, gzdoom and zandronum. Tried to test with Brutal Doom mod and scythe wad, worked too. There is not critical bug, see attached image.  Also why it is necessary to select save folders? Can't I use default ones?
![screenshot - 12 10 2015 - 17 33 39](https://cloud.githubusercontent.com/assets/14122557/10430399/a6874924-7107-11e5-8ce2-1bb2b485a04d.png)

**Comment by FreaKzero** [comment]
Thanks alot mate!

Since i did this thing "mostly" for myself... the idea behind the save folders are the following:
Im using Zandronum for few things - and gzDoom for few things, but things can become very shitty when you have alot of save files and you dont know which "modconstellation" you have used.

So the savesystem goes this way:
enginefolder/name of your customized list or when you have no list its "Untitled" 

You can also just throw in all savefolders in 1 single folder - that was just a feature for myself because i have all the time alot of savegames and always was confused.

**Comment by FreaKzero** [comment]
@Serasar 
Linux 4.0 Release is now here:
https://github.com/FreaKzero/ssgl-doom-launcher/releases/tag/v0.0.4

Again, thank you very much for your help - when you have additional ideas or recommendations just post it here. When you want ill mention you as linux tester in the next Release in the About Dialog.
