### ISSUE TITLE
Feature request: support closing SSGL when game exits

### ISSUE THREAD

**Issue by duganchen** [FreaKzero/ssgl-doom-launcher#36]
May I please request that SSGL supports closing the application when the game exits? I'd imagine it would show as a checkbox in settings.

My use case is this. I play DOOM with a Steam Controller. That means that I launch SSGL from Steam. I launch gzdoom from SSGL. Steam detects DOOM running and sets up the overlay, which makes my Steam Controller work. What I've found pretty consistently is that if I close DOOM and relaunch it from SSGL, my Steam Controller gets confused. I'd also prefer to be back at Steam after closing DOOM, rather than being back at SSGL and having Steam know that it's still running.

Thanks.

**Comment by duganchen** [comment]
Worth mentioning that [(Q)ZDL](https://github.com/qbasicer/qzdl) has an equivalent "Close on launch" option.

**Comment by FreaKzero** [comment]
Some news there:
Im planning a complete overhaul / architecture change for SSGL - which will be the official Version 2. Whats pretty funny - because i have to do that because of a better "TV Experience" for myself. I still dont know if i can implement that with NWJS (dont know if i can kill it when a child process ends) but i can for sure in SSGL V2 with the new Stuff i want to use.

Will try to implement that in my last (!) release for SSGL V1.

**Comment by FreaKzero** [comment]
Fixed with https://github.com/FreaKzero/ssgl-doom-launcher/commit/2bc17b24d9b11c76ddae54d119a139df6c7e4c8f

**Comment by FreaKzero** [comment]
Closing this due to: https://github.com/FreaKzero/ssgl-doom-launcher/blob/v1/README.md
