### ISSUE TITLE
Possibility to add folders as regular pk3/wad mods

### ISSUE THREAD

**Issue by schvabodka-man** [FreaKzero/ssgl-doom-launcher#37]
Hi there! It would be nice if you'll add a possibility to attach folders in WAD folder as mods. In fact there are plenty of mods that come in form of folder with some files, not a packaged pk3/wad file. Also, it can be suitable for mod developers

**Comment by FreaKzero** [comment]
Will most likely come after this release.
The coming release will introduce user configureable modfile extensions (pk3, pk7, wad ...)

Since your idea is pretty advanced and i think an ui will most likely be "configuration hell/overkill" i would say i introduce something like a dotfile .ssgl-usefolder in the folder which should be recognized in ssgl as an own mod.

There is no other "clean" ui solution for this - and i dont want to loose the "loadflow" - since its in my opinion the "main feature" of SSGL (minimal and fast)
