### ISSUE TITLE
Linux Version Releasing

### ISSUE THREAD

**Issue by FreaKzero** [FreaKzero/ssgl-doom-launcher#72]
Currently i have no idea in what i should package SSGL - would need help/directions from someone on this.

**Comment by mhatvan** [comment]
For Linux, the most common packaging is AppImage, .deb or snap packages.

I would recommend packaging SSGL as a snap: https://snapcraft.io/store

It is auto-updating, containerized for security and easy to install and remove.

**Comment by scar45** [comment]
There's also an [outdated AUR package](https://aur.archlinux.org/packages/ssgl-doom-launcher-git/) which uses this Git repo in its [PKGBUILD script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ssgl-doom-launcher-git), with the maintainer's contact details at the top. I will try to get in touch with him to see if that can be updated/tested so that Arch Linux users can continue to get the latest builds from `master`.

**Comment by scar45** [comment]
@mdeguzis - Are you by chance the maintainer of the [current SSGL package on the AUR](https://aur.archlinux.org/packages/ssgl-doom-launcher-git/)? We're looking to update everything to the latest codebase rewrite from @FreaKzero, and could use your help. I have not maintained any AUR packages myself, but I would certainly be up for it with a little bit of guidance.

Thanks in advance for any help you can provide!

**Comment by FreaKzero** [comment]
Will try to make a smap image and send you directly via DM in discord for testing @scar45 

Would be awesome if that works
@mhatvan thank you also for your input :D

**Comment by FreaKzero** [comment]
Was able to build Snaps => Can be found here: 
https://github.com/FreaKzero/ssgl-doom-launcher/releases/tag/v2.0.0-devpreview.13

**Comment by mhatvan** [comment]
According to this reddit thread, snaps are compatible for most linux distros, including Arch: https://www.reddit.com/r/linux/comments/7tbqnf/as_a_dev_should_i_adopt_snapcraft/
